services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ssl-toolkit-backend
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SECRET_KEY:-development-secret-key}
      - FLASK_ENV=${FLASK_ENV:-production}
    volumes:
      - /tmp/ssl-toolkit:/tmp/ssl-toolkit
    networks:
      - ssl-toolkit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ssl-toolkit-frontend
    restart: unless-stopped
    networks:
      - ssl-toolkit-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: ssl-toolkit-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl
    networks:
      - ssl-toolkit-network
      - traefik
    depends_on:
      - backend
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.ssl-toolkit.rule=Host(`ssl-toolkit.yourdomain.com`)"
      - "traefik.http.routers.ssl-toolkit.entrypoints=websecure"
      - "traefik.http.routers.ssl-toolkit.tls.certresolver=letsencrypt"
      - "traefik.http.services.ssl-toolkit.loadbalancer.server.port=80"
      # Optional: Redirect HTTP to HTTPS
      - "traefik.http.routers.ssl-toolkit-http.rule=Host(`ssl-toolkit.yourdomain.com`)"
      - "traefik.http.routers.ssl-toolkit-http.entrypoints=web"
      - "traefik.http.routers.ssl-toolkit-http.middlewares=ssl-toolkit-redirect"
      - "traefik.http.middlewares.ssl-toolkit-redirect.redirectscheme.scheme=https"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ssl-toolkit-network:
    driver: bridge
  traefik:
    external: true

volumes:
  ssl-data:
    driver: local

